# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-13 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=50, verbose_name='购物车编号')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='购物车中商品创建时间')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
            ],
            options={
                'verbose_name_plural': '购物车',
                'db_table': 'car_items',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='shop_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('slug', models.SlugField(help_text='根据name生成的，用于生成页面URL，必须唯一', unique=True, verbose_name='Slug')),
                ('desc', models.TextField(verbose_name='名称描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活（当前分类是否可用）')),
                ('meta_keywords', models.CharField(help_text='meta关键词，有利于SEO，用逗号分割', max_length=255, verbose_name='Meta关键词')),
                ('meta_desc', models.CharField(help_text='meta描述', max_length=255, verbose_name='Meta描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '分类表',
                'db_table': 'categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='shop_pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('slug', models.SlugField(help_text='根据name生成的，用于生成页面URL，必须唯一', max_length=255, unique=True, verbose_name='Slug')),
                ('brand', models.CharField(max_length=50, verbose_name='品牌')),
                ('sku', models.CharField(max_length=50, verbose_name='计量单位')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='现价')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='原价')),
                ('image', models.ImageField(max_length=50, upload_to='products/', verbose_name='图片')),
                ('is_active', models.BooleanField(default=True, verbose_name='设为激活')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='标为热销')),
                ('is_featured', models.BooleanField(default=False, verbose_name='标为推荐')),
                ('quantity', models.IntegerField(verbose_name='商品数量')),
                ('desc', models.TextField(verbose_name='商品描述')),
                ('meta_keywords', models.CharField(help_text='meta关键词标签，逗号分隔', max_length=255, verbose_name='Meta关键词')),
                ('meta_desc', models.CharField(help_text='meta描述标签', max_length=255, verbose_name='Meta描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('categories', models.ManyToManyField(to='shop_app.shop_cat')),
            ],
            options={
                'verbose_name_plural': '商品表',
                'db_table': 'shop_pro',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='shop_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, null=True, verbose_name='密码')),
                ('sex', models.BooleanField(choices=[(0, '男'), (1, '女'), (2, '保密')], default=2, max_length=1)),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='邮箱')),
                ('face', models.ImageField(max_length=50, upload_to='user/', verbose_name='用户头像')),
                ('regTime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AlterField(
            model_name='shop_admin',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='shop_admin',
            name='username',
            field=models.CharField(max_length=20, null=True, unique=bool, verbose_name='管理员名称'),
        ),
        migrations.AddField(
            model_name='caritem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.shop_pro'),
        ),
    ]
