# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-13 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_auto_20170813_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop_user',
            options={'ordering': ['-id'], 'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
    ]
