# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-13 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_cat',
            name='proname',
            field=models.CharField(max_length=50, null=True, verbose_name='分类商品名称'),
        ),
    ]
