# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-13 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_shop_cat_proname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_cat',
            name='proname',
        ),
    ]
