# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-13 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_auto_20170813_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_cat',
            name='proname',
            field=models.CharField(max_length=50, null=True, unique=bool, verbose_name='商品小分类'),
        ),
        migrations.AlterField(
            model_name='shop_cat',
            name='name',
            field=models.CharField(max_length=50, verbose_name='分类名称'),
        ),
    ]
