# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-13 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_auto_20170813_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_cat',
            name='name',
            field=models.CharField(max_length=50, unique=bool, verbose_name='分类名称'),
        ),
    ]
