# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-18 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_auto_20170814_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop_catpro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=bool, verbose_name='商品材质名称')),
            ],
            options={
                'verbose_name_plural': '商品材质分类',
                'db_table': 'shopcarpro',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='shop_cat',
            options={'ordering': ['-proname'], 'verbose_name_plural': '分类表'},
        ),
        migrations.AlterField(
            model_name='shop_pro',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='商品名称'),
        ),
    ]
