# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-18 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0013_auto_20170818_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop_cat',
            options={'ordering': ['-proname', 'name'], 'verbose_name_plural': '分类表'},
        ),
        migrations.AddField(
            model_name='shop_pro',
            name='shopcatpro',
            field=models.ManyToManyField(to='shop_app.shop_catpro'),
        ),
        migrations.AlterField(
            model_name='shop_cat',
            name='name',
            field=models.CharField(max_length=50, verbose_name='分类名称'),
        ),
    ]
