# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-18 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0014_auto_20170818_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_cat',
            name='shopcat',
            field=models.ManyToManyField(null=True, to='shop_app.shop_catpro'),
        ),
    ]
