# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-18 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0015_auto_20170818_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_cat',
            name='shopcat',
        ),
        migrations.RemoveField(
            model_name='shop_pro',
            name='shopcatpro',
        ),
        migrations.DeleteModel(
            name='shop_catpro',
        ),
    ]
